### DISCUSSION TITLE
Struggling to get working in docker and a bit lost now

### DISCUSSION THREAD

**Discussion by crispybegs** [mxpv/podsync#728] [General]
hi, i love the idea of this but i'm struggling to get it working. I'm sure I must be getting something wrong but I'm not sure what

This is my compose:

version: '2.2'

```
services:
  podsync:
    container_name: podsync
    image: mxpv/podsync:latest
    restart: unless-stopped
    ports:
      - 8190:80
    volumes:
      - /media/crispy/NAS_4TB_1/media/podcasts:/app/data/
      - /home/crispy/docker/podsync/config/config.toml:/app/config.toml
```

When I start up the service, the logs just say this and it never changes:

`time="2024-05-26T18:19:45Z" level=info msg="Using log file: podsync.log"
`

This is my config.toml

```
[server]
port = 8190

[storage]
type = "local"
[storage.local]
data_dir = "/app/data" 

[tokens]
youtube = "xxxxx_redacted_" 

[feeds.ID1]
url = "https://www.youtube.com/channel/UCH-6-0uCbVRZgoOMAPGbxwg"
page_size = 5
update_period = "12h"
quality = "high" # "high" or "low"
format = "audio" # "audio", "video" or "custom"

opml = true

clean = { keep_last = 10 }

private_feed = true

[database]
badger = { truncate = true, file_io = true }

[downloader]
self_update = true
timeout = 15

[log]
65 filename = "podsync.log"
66 max_size = 50 # MB
67 max_age = 30 # days
68 max_backups = 7
69 compress = true
70 debug = false
```

As you can see, I set the GUI port as `8190`, but when I visit that address no page loads, just "This site can’t be reached" etc

What have I messed up here?
