### DISCUSSION TITLE
Bind port 4443 to 80 [Docker + Traefik]

### DISCUSSION THREAD

**Discussion by Oschly** [mxpv/podsync#735] [General]
Hello!
I have a problem with podsync. I have podsync set with Traefik and Docker like that: 

```
version: '2.2'

services:
  podsync:
    container_name: podsync
    ports:
      - 4443:4443
    image: mxpv/podsync:latest
    restart: always
    labels:
            - traefik.docker.network = [name]
            - traefik.enable = true
            - traefik.backend = Podsync
            - traefik.frontend.rule = Host:sub.domain.tld:4443
            - traefik.port = 80
    volumes:
      - /path/:/app/data/
      - /path/config.toml:/app/config.toml
```

with given config:
```
[server]
port = 4443
hostname = "http://sub.domain.tld:4443"
data_dir = "/app/data" # Don't change if you run podsync via docker
```

site works, but the problem is that pocket casts after adding it to feed, tries to take podcasts from port 80. I've tried to set everything as 4443, but it doesn't work. And important is that I can't bind it to 80 inside docker-compose, because other service owns that (domain.tld:80).
