### ISSUE TITLE
strings cannot contain newlines

### ISSUE THREAD

**Issue by weigeloveu** [mxpv/podsync#106]
failed to load configuration file             error="failed to load config file: Near line 3 (last key parsed 'server.data_dir'): strings cannot contain newlines"

[server]
port = 8080
data_dir = "D:\" # Don't change if you run podsync via docker

**Comment by mxpv** [comment]
I wasn't able to reproduce the problem with the configuration you provided.
However I've received that error when `data_dir` actually had a new line, like this:
```toml
[server]
port = 8080
data_dir = "D:
" # Don't change if you run podsync via docker
```

Please check your configuration and get back if you still experience issues with this.
