### ISSUE TITLE
Cover Art now being ignored 

### ISSUE THREAD

**Issue by Rumik** [mxpv/podsync#125]
Since updating a day ago, the artwork I’m specifying for each podcast is now being ignored, using the Embedded artwork instead. Has anything changed in that area?

Thanks

**Comment by mxpv** [comment]
I forgot to update README. I added more customizations and had to move those fields to a separate sections. You'd need to update your config to:
```toml
[feeds]
  [feeds.ID1]
  url = "{FEED_URL}" 
  ...
  custom = { cover_art = "{IMAGE_URL}", category = "TV", explicit = true, lang = "en" }
 
```
