### ISSUE TITLE
Support for SponsorBlock

### ISSUE THREAD

**Issue by hatzel** [mxpv/podsync#136]
It would be great to block sponsor reads as collected in [SponsorBlock](https://github.com/ajayyy/SponsorBlock). This might involve a lot of work (i.e. calling ffmpeg manually) as modifying the actual data would be required.
In principle, however, the feature would not be immensely complicated. FFmpeg can be passed cut-lists and can if desired cut only at key-frames. The SponsorBlock API can easily be used to retrieve the blocked segments.

**Comment by hatzel** [comment]
Turns out this is a lot easier than I thought. Supplying the [right arguments](https://superuser.com/questions/681885/how-can-i-remove-multiple-segments-from-a-video-using-ffmpeg) to youtube-dl's `--postprocessor-args` should do the trick, so if you'd be willing to merge something like this (as an opt-in setting in the config file) I'd probably crank out a PR for this in the next few days or weeks.

I'd suggest having one global flag to set up a sponsorblock default which can than be overwritten on a per feed basis.

Maybe something like this:
```toml
[sponsorblock]
enable = true
url = "https://sponsor.ajay.app"

[feeds]
  [feed.my_feed]
  ...
  sponsorblock = false
```
