### ISSUE TITLE
tmp folder (in container)

### ISSUE THREAD

**Issue by psyciknz** [mxpv/podsync#146]
Not quite sure what is going in the tmp folder, mine was sitting at 14gb.
Is it temporary files going in there, and what is supposed to clean it up?   I run in docker
```
 podsync:
    container_name: podsync
    restart: always
    environment:
      - TZ=Pacific/Auckland
      - PUID=1000
      - PGID=1000
    image: mxpv/podsync:latest
    networks:
      - media
    ports:
      - "8013:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /media/serverfolders/Videos_To_Check/podsync:/app/data/
      - /hdd/docker-data/media/podsync/config.toml:/app/config.toml
```

The image was current as at when the cleanup was introduced.   I've now since just pulled another image today just in case that was a bug.
