### ISSUE TITLE
issues with large files and slow platform

### ISSUE THREAD

**Issue by grasegger** [mxpv/podsync#205]
**Expected behaviour:**

Downloaded files are moved to the data_dir of podsync. 

**Observed behaviour:**

Subfolder with active ffmpeg-process merging audio and video gets unlinked before process is finished. The ffmpeg-process will execute without an error, but produced files are basically discarded right after. Podsync already is handling the next job. 

This only happens for large files for me, so I think running podsync on a raspi zero w is part of the problem. But since everything works correctly with smaller files (for the same feed!) I came to the conclusion that podsync job control might not handle this very well. 

*Working config:*
```toml
  [feeds.gronkh_cb_2077]
  url = "https://www.youtube.com/channel/UCYJ61XIK64sp6ZFFS8sctxw"
  page_size = 9
  update_period = "30m"
  quality = "low"
  format = "video"
  max_height = 480
  filters = { title = "CYBERPUNK 2077.*" }
  clean = { keep_last = 2 }
```

*Broken config:*
```toml
  [feeds.gronkh_cb_2077]
  url = "https://www.youtube.com/channel/UCYJ61XIK64sp6ZFFS8sctxw"
  page_size = 9
  update_period = "30m"
  quality = "high"
  format = "video"
  max_height = 1080
  filters = { title = "CYBERPUNK 2077.*" }
  clean = { keep_last = 2 }
```

**Additional Details**
- When downloaded directly the download is working
- There is enough space on the device
- Podsync daemon log contains no errors

I tried to look at the source to maybe find something I can do, but I don't know go and didn't find the point where this error should be handled.
