### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by gthbusrr** [mxpv/podsync#220]
Environment: Docker
Version: v2.4.0

<img width="626" alt="Screenshot 2021-03-12 at 16 46 15" src="https://user-images.githubusercontent.com/77537216/110915501-9e637b80-830f-11eb-8a01-f076c582c53f.png">

**Comment by mxpv** [comment]
Can you provide configuration you use?

**Comment by gthbusrr** [comment]
```
version: "2"

services: 
    podsync-vpn:
        image: ilteoood/docker-surfshark:latest
        container_name: podsync-vpn
        environment: 
            - SURFSHARK_USER=******************
            - SURFSHARK_PASSWORD=******************
            - SURFSHARK_COUNTRY=**
            - SURFSHARK_CITY=*****
        cap_add: 
            - NET_ADMIN
        labels:
            - "com.centurylinklabs.watchtower.monitor-only=true"
        devices:
            - /dev/net/tun
        ports:
            - '****:****'
        restart: always
        dns:
            - 1.1.1.1
    podsync:
        container_name: podsync
        image: mxpv/podsync:latest
        restart: always
        depends_on:
            - podsync-vpn
        environment:
            - TZ=Asia/Hong_Kong
        network_mode: service:podsync-vpn
        volumes:
            - ./data:/app/data/
            - ./config.toml:/app/config.toml
```
