### ISSUE TITLE
Doc on using ngrok for overcast.fm?

### ISSUE THREAD

**Issue by matschaffer** [mxpv/podsync#239]
I was trying to set up podsync to listen to the next.js 2021 conference videos on a long road trip, but I couldn't seem to add the feed to overcast on iOS.

I just get this.

![IMG_E6385F3BC403-1](https://user-images.githubusercontent.com/690/139561466-3b71d344-334b-4a27-9726-132ba5915b67.jpeg)

The same URL loads fine in a browser at the same URL. I can even open the URL in iOS chrome and save the file back to dropbox.

So it didn't seem like a networking problem.

Turns out putting https://ngrok.com/ in front of my local server did the trick.

I realize this is really an overcast limitation rather than podsync, but given most people are probably running podsync locally I was thinking maybe the readme should include a note about setting up a public URL for use with overcast.

**Comment by matschaffer** [comment]
You know.... now that I write that. I might also be because I finally thought to set server.hostname once I set up ngrok.

I'll have to try it again setting sever.hostname to my on-network IP and see if that works.

**Comment by matschaffer** [comment]
Huh. Interestingly enough `hostname = "http://192.168.86.25:8080` had the same "Timed Out" response from overcast.

So guess a public URL is a requirement for overcast? Anyway. I thought maybe a doc could be helpful for folks trying to do a similar thing.

**Comment by jeyemwey** [comment]
Hi, just for documenting the issue: Overcast has servers that check if the feed has new podcasts. Since your IP is local to your network (RFC1918, 192.168.x.y), those servers can not locate your feed.

If you punch a hole through your firewall (i.e. by using ngrok), those servers are able to catch your feed and everything will work just fine.

**Comment by matschaffer** [comment]
My latest workaround for this is to copy everything locally and use VLC for iOS. The speed control isn't as good as overcast, but it's at least better than dropbox which has no speed option.

**Comment by wilt00** [comment]
Adding to this documentation for anyone wanting to run a podsync server on their home internet for use with Overcast; I don't recommend using ngrok, since on the free tier the url changes whenever you restart the service. In the past I've successfully used [Cloudflare Tunnel](https://developers.cloudflare.com/tunnel/), free if you already own a domain name, and currently I'm using [Tailscale Funnel](https://tailscale.com/docs/features/tailscale-funnel) which is as easy to use as ngrok and gives you a stable url without needing to buy a domain.

You'll also need to change `hostname` in `config.toml` to whatever the public-facing url of your server is, or else all downloads will fail. For Tailscale it'll look something like
```toml
[server]
port = 8080
hostname = "https://computername.tail####.ts.net" # Actual url will be displayed in the terminal when you run tailscale
no_index = true   # keep google from indexing your server
no_listing = true # set this true when you're finished troubleshooting to keep people from snooping on your feeds
```
