### ISSUE TITLE
Can't download episode when set the feed's config page_szie value to 1

### ISSUE THREAD

**Issue by laraws** [mxpv/podsync#245]
When I set the feed's config page_szie value to 1, there would be not episode downloaded. I find there's a limit at the code at this [location](https://github.com/mxpv/podsync/blob/cc9fcb42176c6bfd990149c0c61dd3b023c24d44/cmd/podsync/updater.go#L204). Why does the code reduce to download the last  episode?

The feed config likes this:
```toml
  [feeds.test]
  url = "https://www.youtube.com/playlist?list=PLnKtcw5mIGURz0MbTIvOwZM5_FZGVGxU2" # URL address of a channel, group, user, or playlist.
  page_size = 1 # The number of episodes to query each update (keep in mind, that this might drain API token)
  update_period = "6h" # How often query for updates, examples: "60m", "4h", "2h45m"
  quality = "high" # or "low"
  format = "audio" # or "audio"
  clean = { keep_last = 3 }
```
The log likes this:

![image](https://user-images.githubusercontent.com/40230381/147177357-d44f1adb-1d2d-45b4-99d8-542000c797de.png)

Please fix it. Thanks.
