### ISSUE TITLE
YT changed channels to handles

### ISSUE THREAD

**Issue by kamil7732** [mxpv/podsync#469]
hi guys,
i guess we need to do an update

channels aren't visible anymore as https://www.youtube.com/channel/UC,....
but now they're as https://www.youtube.com/@handle

currently podsync doesn't work with the new url structure.

**Comment by Th0masL** [comment]
I've added a [PR](https://github.com/mxpv/podsync/pull/475) that should fix that

**Comment by Th0masL** [comment]
Actually my PR is not yet working, but please find a workaround below.

Basically if you find a way to know/get the Channel name, you should be good.

So the idea is to use CURL to query the page using the handle URL, and get the channel ID from the HTML code:

```bash
curl -D- --silent https://www.youtube.com/@NASA | tr ',' '\n' | grep -i -E "externalId" 
"externalId":"UCLA_DiR1FfKNvjuUpBHmylQ"
```

Then you can define your feed using the `/channel/xxx` URL :

```toml
[feeds]
  [feeds.NASA]
  url = "https://www.youtube.com/@NASA" # not working
  url = "https://www.youtube.com/channel/UCLA_DiR1FfKNvjuUpBHmylQ" # should be working
```
