### ISSUE TITLE
Feature Request: Run command on feed update

### ISSUE THREAD

**Issue by wilt00** [mxpv/podsync#502]
I'd like to be able to trigger an HTTP request when a feed completes updating if there are new episodes available. Some use cases for this:

* Overcast has [an API to trigger a feed refresh](https://overcast.fm/podcasterinfo) (This is the one I want)
* [Podping](https://podcasting20.substack.com/p/podping) is a similar (public-only) update mechanism, although I'm not sure what apps if any use it yet
* Sending notifications about new episodes through a messaging app like Discord or Slack

I'm happy to work on this myself, if you'd accept a PR for it. I'm not sure what an appropriate config setting for this would look like, though. I have a couple of ideas:

1. A new `webhook` option:

```toml
[feeds]
  [feeds.ID1]
    ...
    webhook = { method = "POST", url = "https://mywebsite.biz/ping", body = "{\"url\": \"$FEED_URL\"}" }
```

2. A more generic `on_update` option that runs a command or script when the update finishes:

```toml
[feeds]
  [feeds.ID1]
    ...
    on_update = "curl -X POST --data \"{\\\"url\\\": \\\"$FEED_URL\\\"}\" https://mywebsite.biz/ping"
```

This would allow more complex integrations, for example, as suggested in another recent issue, uploading new episodes to Archive.org using [their API](https://archive.org/developers/tutorial-create-item.html). Realistically, though, it would probably require users to build their own docker container to do anything nontrivial (I don't think curl is included in the alpine docker image, for one).

For both of these I'm envisioning some kind of template variable system where feed properties are exposed and can be inserted into the strings.
