### ISSUE TITLE
Not Found on Path

### ISSUE THREAD

**Issue by TobiTenno** [mxpv/podsync#547]
```toml
[server]
port = 8099
hostname = "https://something.domain.tld:443/podcasts/"
path = "podcasts"
```
(also attempted with `bind_address = "*"`)

docker.compose.yml:
```yaml
services:
  podsync:
     container_name: podsync
     image: mxpv/podsync:latest
     restart: always
     ports:
       - 8099:8099
     volumes:
       - ./data:/app/data/
       - ./config.toml:/app/config.toml
 ```
 
 nginx:
```nginx
    location /podcasts/ {
        proxy_pass              http://localhost:8099/podcasts;
        proxy_set_header        Host            $http_host;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Scheme        $scheme;
        proxy_set_header        X-Script-Name   podcasts;
    }
```

when I attempt to visit https://something.domain.tld/podcasts/ID1, I end up with `404 page not found`.

(i've tested the config for downloading and seeing a specific ID locally and it works, that part i'm not concerned about)

this is different compared to if i'm hitting wiht the server down or inaccessible, but I can't find where i'm missing something or misconfigured.
