### ISSUE TITLE
Issues with youtube dl

### ISSUE THREAD

**Issue by gelof2022** [mxpv/podsync#598]
Hi,

I had no issues running pod_sync over the last few years. Then I relaunched pod_sync using a docker compose:

```
version: "2.2"
services:
  podsync:
    container_name: podsync
    image: mxpv/podsync:latest
    restart: always
    environment:
      - TZ=Australia/Sydney
    ports:
      - 7090:7090
    volumes:
      - /volume1/docker/podsync/data:/app/data/
      - /volume1/docker/podsync/config.toml:/app/config.toml
networks: {}
```

I now get the following error when pod_sync starts:

[debug] Command-line config: ['--update', '--verbose'] [debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI) [debug] yt-dlp version 2022.11.11 [8b64402] (zip) [debug] Python 3.10.8 (CPython x86_64 64bit) - Linux-3.10.108-x86_64-with (OpenSSL 1.1.1q 5 Jul 2022) [debug] exe versions: ffmpeg 5.0.1 (setts), ffprobe 5.0.1 [debug] Optional libraries: sqlite3-2.6.0 [debug] Proxy map: {} [debug] Loaded 1723 extractors [debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest ERROR: Unable to obtain version info; Please try again later or Visit https://github.com/yt-dlp/yt-dlp/releases/latest

How do I resolve this?

Thanks,

Oleg
