### ISSUE TITLE
Nothing Works

### ISSUE THREAD

**Issue by kpirnie** [mxpv/podsync#656]
```
time="2024-09-06T11:45:03Z" level=error msg="youtube-dl error: /tmp/podsync-3604958398/-bdOQIy_0tw.%(ext)s" error="failed to execute youtube-dl: exit status 1"
time="2024-09-06T11:45:03Z" level=error msg="[youtube] -bdOQIy_0tw: Downloading webpage\n[youtube] -bdOQIy_0tw: Downloading android player API JSON\nWARNING: [youtube] YouTube said: ERROR - Precondition check failed.\nWARNING: [youtube] HTTP Error 400: Bad Request.
```
In error logs

**Comment by garlic-hub** [comment]
I was running into this because I was using `mxpv/podsync` docker image (2 years out of date) instead of the `ghcr.io/mxpv/podsync` image. Once I switched the issue was gone. The README.md needs to be updated

**Comment by garlic-hub** [comment]
See my PR here https://github.com/mxpv/podsync/pull/657

**Comment by Harnas** [comment]
Podsync uses yt-dlp to download from youtube. Last time, Youtube changes their policy, and now yt-dlp have problems with downloading. More about that https://github.com/yt-dlp/yt-dlp/issues/10128

**Comment by muradjabir** [comment]
on docker:  docker exec -it podsync yt-dlp -U
This updates yt-dlp for your current instance only!

**Comment by brothamanben** [comment]
> docker exec -it podsync yt-dlp -U

I did this but I'm still getting download errors, and asked to sign in to confirm that I'm not a bot

**Comment by jeffreygarc** [comment]
> on docker: docker exec -it podsync yt-dlp -U This updates yt-dlp for your current instance only!

I had to run `docker exec -it podsync /usr/bin/youtube-dl -U` instead, and it works now.

**Comment by Dasnap** [comment]
I put together a docker-compose that includes the update step if anyone finds it helpful:

```
services:
  podsync:
    container_name: podsync
    image: ghcr.io/mxpv/podsync:latest
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./data:/data
      - ./config.toml:/app/config.toml
    entrypoint: /bin/sh
    command: -c "youtube-dl -U || echo 'Update failed, continuing...'; exec /app/podsync --config /app/config.toml"
```
